[package]
name = "axum-test-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream", "multipart"] }
http = "0.2.5"
http-body = "0.4.4"
bytes = "1.0"
tower-service = "0.3"
